# render.yaml
# Production-ready n8n deployment with GitOps workflow automation
# Automatically imports workflows and credentials from your repo on every deploy

services:
  - type: web
    name: 8ropy
    env: docker
    region: oregon
    plan: free # Free tier - service spins down after 15 mins of inactivity
    
    # Build custom Docker image from this repository
    dockerfilePath: ./Dockerfile
    
    # Auto-deploy on pushes to main branch
    autoDeploy: true
    branch: main
    
    healthCheckPath: /healthz

    envVars:
      # --- Core n8n Settings ---
      - key: N8N_HOST
        value: 0.0.0.0
      - key: PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: https://n8n-latest-ed1u.onrender.com/
      - key: N8N_ENCRYPTION_KEY
        value: "1297dcf6-e668-44ee-aff8-b406e1a99f38"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "false"

      # --- Supabase Database Connection ---
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-0-eu-west-1.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: "6543"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.yakpjriyzkoutkkxcajb
      - key: DB_POSTGRESDB_PASSWORD
        sync: false # Set this manually in Render Dashboard for security
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: DB_POSTGRESDB_SSL
        value: "true"

      # --- Performance & Stability ---
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: GENERIC_TIMEZONE
        value: America/Oragon
      - key: TZ
        value: America/Oragon 
      - key: N8N_LOG_LEVEL
        value: error 

      # --- Data Pruning (keeps database lean) ---
      - key: EXECUTIONS_DATA_PRUNE
        value: "true"
      - key: EXECUTIONS_DATA_MAX_AGE
        value: "336" # 14 days
      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        value: "none"
      - key: EXECUTIONS_DATA_SAVE_ON_ERROR
        value: "all"
